name: Milkshake builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo import
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: jdk boot
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: bzl boot
        uses: abhinavsingh/setup-bazel@v3

      - name: bzl build
        run: bazel build @milkshake//mod --output_groups=default,executable

      - name: Upload artifact
        run: |
          mkdir -p mod
          cp bazel-bin/mod/mod.jar ./mod/
          
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add mod/mod.jar
          git commit -m 'Automated build: Update mod.jar'
          git push
